title: Populate Summer School (Intro to math epi)
logo: /assets/img/Gemini-generated-viruses-bacteria-2.jpeg
description: This is my course material for the June 2025 Populate Summer School held in Grasse
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
