title: 3MC-PIMS-ICMS 2024 (Intro to math epi)
logo: /assets/img/Gemini_Generated_Image_ypohkuypohkuypoh.jpeg
description: This is my course material for the December 2024 3MC-PIMS-ICMS Winter School held at ICMS in Edinburgh..
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
